name: Continuous Integration Java 17

on:
  push:
    branches-ignore:
      - "main"
      - "old-master"

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      ## Configure JDK
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0 v5
        with:
          java-version: '17'
          java-package: 'jdk+fx'
          cache: 'maven'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn -s .m2/settings.xml -gs .m2/settings.xml -B verify -Dmaven.test.failure.ignore=true
        env:
          NEXUS_USERID: ${{ secrets.PUB_NEXUS2_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.PUB_NEXUS2_PASSWORD }}
          NEXUS_URL: ${{ vars.LEVIGO_MAVEN2_ALL_REPOSITORIES }}

      ## Publish test report
      - name: Publish Test Report
        id: test-report
        uses: ScalableCapital/action-surefire-report@1e92f48016e566e4eed2d81560edbfe0f524cfb7 # v2.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_test_failures: true
          fail_if_no_tests: false
