name: Continuous Delivery Java 11

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      JSCC_VERSION_PREFIX: '1.'
      JSCC_TAG_PREFIX: '1.'


    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
        java-package: 'jdk+fx'
        cache: 'maven'

    - name: Bump version and create tag
      id: semanticversion
      uses: mathieudutour/github-tag-action@v6.2
      with:
        release_branches: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ${{ env.JSCC_TAG_PREFIX }}

    - name: Verify and print new build number
      run: |
        if echo '${{ steps.semanticversion.outputs.new_tag }}' |grep -Eq '^${{ env.JSCC_TAG_PREFIX }}[0-9]+[.][0-9]+[.][0-9]+$'; then
          echo New version '${{ steps.semanticversion.outputs.new_version }}', Changelog '${{ steps.semanticversion.outputs.changelog }}'
        else
          echo 'unexpected tag format - aborting'
          exit -1
        fi

    - name: Set version to environment variable
      run: echo "NEW_VERSION=${{ env.JSCC_VERSION_PREFIX }}${{ steps.semanticversion.outputs.new_version }}" >> $GITHUB_ENV

    - name: run mvn set version
      run: |
        mvn -s .m2/settings.xml versions:set -DnewVersion=${{ env.NEW_VERSION }}
      env:
        NEXUS_USERID: ${{secrets.NEXUS_USERID}}
        NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}

      ## Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
         languages: java
    
    - name: Build with Maven
      run: mvn -s .m2/settings.xml -gs .m2/settings.xml -B package --file pom.xml
      env:
        NEXUS_USERID: ${{secrets.NEXUS_USERID}}
        NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: create release and upload release asset
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ steps.semanticversion.outputs.new_version }}
        tag_name: ${{ steps.semanticversion.outputs.new_tag }}
        files: |
          ./target/jadice-server-converter-client-${{ env.NEW_VERSION }}.exe
